max_velocity = 1.0 #m/s
max_acceleration = 0.80 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    x = 187.0 #approximate
    y = 53.0 #approximate
    angle = 330.0 #approximate
[end_pose]
    x = 144.0
    y = 161.62
    angle = 330.0 #approximate

[[internal_points]]
    x = 165.5
    y = 107.31