max_velocity = 1.0 #m/s
max_acceleration = 1.0 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.5 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    x = 2.02
    y = 1.06
    angle = 0.0

[end_pose]
    x = 4.5
    y = 0.98
    angle = 0.0 

[[internal_points]]
    x = 3.4
    y = 1.0