max_velocity = 2.0 #m/s
max_acceleration = 1.2 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 30.0 #degrees

[start_pose]
    x = 0.89
    y = 6.58
    angle = 60.0
[end_pose]
    x = 2.59
    y = 6.86
    angle = 30.0

[[internal_points]]
    x = 1.74
    y = 6.72