max_velocity = 2.0 #m/s
max_acceleration = 1.2 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    x = 2.59
    y = 4.09
    angle = -30.0 #approximate
[end_pose]
    x = 2.59
    y = 5.54
    angle = 0.0 #approximate

[[internal_points]]
    x = 2.29
    y = 5.05