max_velocity = 1.0 #m/s
max_acceleration = 0.80 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 90.0 #degrees

[start_pose]
    x = 2.59
    y = 4.09
    angle = -30.0 #approximate
[end_pose]
    x = 2.89
    y = 5.24
    angle = 90.0 #approximate

[[internal_points]]
    x = 2.44
    y = 4.615