max_velocity = 1.0 #m/s
max_acceleration = 0.8 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    x = 2.89
    y = 5.24
    angle = 90.0
[end_pose]
    x = 2.89
    y = 5.54
    angle = 0.0

[[internal_points]]
    x = 2.89
    y = 5.34